# Generated by Django 3.2.10 on 2022-02-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='envelope',
            fields=[
                ('envelope_id', models.AutoField(primary_key=True, serialize=False, verbose_name='红包id')),
                ('uid', models.IntegerField(default=None, verbose_name='用户id')),
                ('value', models.IntegerField(default=True, verbose_name='红包面值')),
                ('opened', models.BooleanField(default=False, verbose_name='红包状态')),
                ('snatch_time', models.DateTimeField(auto_now_add=True, verbose_name='获取时间')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('amount', models.IntegerField(default=0, verbose_name='总金额')),
            ],
        ),
    ]
