# Generated by Django 3.2.10 on 2022-02-16 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelope',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.user'),
        ),
    ]
