# Generated by Django 3.2.10 on 2022-02-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_envelope_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelope',
            name='snatch_time',
            field=models.IntegerField(default=0, verbose_name='获取时间'),
        ),
        migrations.AlterField(
            model_name='envelope',
            name='value',
            field=models.IntegerField(default=0, verbose_name='红包面值'),
        ),
    ]
