# Generated by Django 3.2.10 on 2022-02-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20220217_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelope',
            name='snatch_time',
            field=models.BigIntegerField(default=0, verbose_name='获取时间'),
        ),
    ]
